[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "REEMPLAZAR_CON_URL_SUPABASE_CLIENTE"
  VITE_SUPABASE_ANON_KEY = "REEMPLAZAR_CON_ANON_KEY_CLIENTE"
  VITE_SCHOOL_NAME = "REEMPLAZAR_CON_NOMBRE_CORTO"
  VITE_SCHOOL_CODE = "REEMPLAZAR_CON_CODIGO"
  VITE_BRANCH_NAME = "REEMPLAZAR_CON_NOMBRE_COMPLETO"
  RESEND_API_KEY = "REEMPLAZAR_CON_API_KEY_RESEND"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
